language: node_js
dist: trusty
sudo: false
node_js: 6
cache:
  directories:
    - node_modules
after_sucess:
  - npm run gh-pages-travis
env:
  global:
    - SSH_KEY="key"
    - GIT_NAME="Elias Meire"
    - GIT_EMAIL="me@eliasmei.re"
    - SOURCE_DIR="storybook-static"
    - DEPLOY_BRANCH="gh-pages"
branches:
  except:
  - gh-pages
