language: node_js
dist: trusty
sudo: required
node_js: 6
cache:
  directories:
    - node_modules
env:
  global:
    secure: Gm2ywnfRzY0vw8AyKL+y0bonuSzpc0vy2oK4Vxfg6wiaxGiQhrGkRjPiahj8URQWjswvoaYcZT0POvqWfd/gQ4WcKDbhKnBylbtN5Y9oMd7GTNH0CCNGWYKOrWWQs/YDwSkdtO7DoNzZ4Na7wWDtHTgltFsVeKQP4Y3M2QTsJS9HTgXMWnPUnIqYCCdsVqRv7xJCiDb2zypoUol/A61m+9o4MAm/gJIzVA6PjKOFfFQuRA4ewCRCvWLDMOwgRCMB1ebeEQZh0ee4Er9WuA+9Yk7t8J3YpLMXlOHF8K/O6bZe1Eo2ffT1ziV8lGhPVrMVc1awQ9qY9JYDzMHEGHAmjzeylPqxtsdAntqV3+JfFUe7FPNG7D6i5ApTKzreus6Ru73as/MLyWjkbBc1nrLVk+XtQl8/R37g3H9lKg3bE3Vc//uhNZ3BLYB77BxmfNUVi+X5Q+nWnnNCzYKGKY2R8GFmjFOPOBQDXN6tOdyROuFY3qFtl09OgyGPvxLJCvtBH+5L3Kvqx6Z6npqRaiyWCHB2kbl7BsqDe5xCDI1T+VSwHhOYh8T9GqYyd9++MviA4WQXY0RUjFZGoJr0DGmrOty8cYqL7ZaxoT6sbL2oNsyjn8NHG0sLuwWqato201jexdL1KXP6BZw871J97g7IwOqLB5lyDuPhTVobLkFHcfU=
